---
sudo: required
dist: trusty

language: generic


services:
  - docker


before_install:
  - sudo apt-get update
  - sudo apt-get --yes --force-yes install python python-pip python-dev docker-engine


install:
  - sudo pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible docker-py


script:
  - ansible --version
  - docker version
  # Basic role syntax check
  - cd deployment; ansible-playbook docker.yml -i inventory --syntax-check
  # login into Docker Hub
  - docker login -p $DOCKER_PASS -e $DOCKER_EMAIL -u $DOCKER_USER
  # Run the role/playbook with ansible-playbook
  - cd deployment; ansible-playbook docker.yml -i inventory --connection=local


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
